### PR TITLE
Overridable S3 API methods

### PR DESCRIPTION
**Pull request by dAnjou**
The main motivation behind this is to be able to add `ExtraArgs` to the upload, e.g. `ExtraArgs={'ContentType': 'image/jpg'})`.

### CODE REVIEW

**Comment by willmcgugan** [comment]
I'm not overly keen on adding these non-FS methods. I think it might set a dangerous precedence that ties code to a specific implementation of the PyFilesystem interface.

You may still be able to convince me otherwise, but I'd me more inclined to add a generic mechanism to the core library that supports your use case.

**Comment by dAnjou** [comment]
There might be better ways to do it, agreed.

But keep in mind that the use case I mentioned is only one of many. All these methods have various arguments that you might want to tweak:
* `upload_fileobj` and `download_fileobj` have `ExtraArgs` (already mentioned) and `Config` for configuring how the network transfer is actually done. `Callback` is pretty interesting as well.
* `copy_object` has a ton of arguments for all kinds of things.
* `generate_presigned_url` has the pretty important `ExpiresIn` argument and it proxies `Params` to `get_object` which also has a ton of arguments.

So far I only needed to pass along the file type (after figuring it out with libmagic) but the expiration time of the URL will probably be the next thing I need to configure. Then I'd need to set `ResponseContentDisposition` dynamically depending on which client is asking for the file and in what context (sometimes the want to just display it in the browser, sometimes they need an attachment). And finally `Callback` might come in handy to update the client on the upload progress.

Generic core mechanisms sound good but they need to be carefully conceptualized and that takes time for all these use cases. So making these methods overridable was the quickest yet still backwards compatible way to fulfill my requirements.

---

PS: Did you have a look at #13 yet, it's much simpler :wink:

**Comment by willmcgugan** [comment]
Afraid I can't get behind these `s3_` methods, but I am sympathetic to your use case. `FS.open` has an `options` argument, which should probably also be on `setbytes` and other shortcut methods, and could be used to pass custom arguments.

In the meantime, how about if we rename `client` to `s3_client` and I officially bless that as a way of getting the Boto interface. In the cases where the FS interface doesn't expose what you need you can do it directly via the `s3_client` object.

**Comment by dAnjou** [comment]
I totally understand. I just needed to come up with something rather quickly. Consider this PR to be more like me trying to raise awareness.

Access to the boto client directly would be kind of besides the point for me because I chose PyFilesystem exactly because it provides a single API no matter what actual filesystem is behind it. So I did what I did because I needed to tweak things that are irrelevant for PyFilesystem's API but relevant for S3's API.

I'd be happy to see a more elegant solution to this (and passing through `options` could be it) but unfortunately I currently don't have the time to spend more time thinking about it.

**Pull request closed without merging**
