### PR TITLE
fetch keys from env if not given

### PR DESCRIPTION
**Pull request by PCouaillier**
Hello,

I got an issue for my application.

I need that s3fs fetch AWS keys from env variables if they exists.

Can you please help me to solve this ?

Those changes makes the job.

If you have any better way to do this I'll take it ^^'

### CODE REVIEW

**Comment by willmcgugan** [comment]
Does it have to be env vars? Could you use the conf files specified by Boto? https://pypi.org/project/boto3/

**Comment by willmcgugan** [comment]
Actually, this _should_ already work. See https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#environment-variables

**Comment by PCouaillier** [comment]
Hello,

Thanks for replying.

The solution you suggest me does not work (already tried previously).

My solution does not work any more. Now i got a : "botocore.exceptions.NoCredentialsError: Unable to locate credentials".

I'll try an other workaround then I'll open an other Merge request.

**Comment by PCouaillier** [comment]
@willmcgugan 

Hello again,

After some more search I found a very simple solution.... Use the AWS_SHARED_CREDENTIALS_FILE to specify './credentials' location...

To be honest I feel a bit ashamed for not seeing it earlier...

Thank you for your time.

**Pull request closed without merging**
